version: "3.7"
services:
  terraform:
    image: hashicorp/terraform:0.14.3
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    volumes:
      - ./src:/opt/
    working_dir: /opt/
