version: 2.1
orbs:
  terraform: 'circleci/terraform@1.1.0'
workflows:
  terraform:
    jobs:
      - terraform/fmt:
          checkout: true
          path: src/
      - terraform/validate:
          context: test-project-terraform
          checkout: true
          path: src/
          requires:
            - terraform/fmt
      - terraform/plan:
          context: test-project-terraform
          checkout: true
          path: src/
          persist-workspace: true
          requires:
            - terraform/validate
      - terraform/apply:
          context: test-project-terraform
          attach-workspace: true
          path: src/
          filters:
            branches:
              only: main
          requires:
            - terraform/plan
